style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/vmware/govmomi
options:
  commits:
    filters:
      Type:
        - govc
        - vcsim
        - chore
  commit_groups:
    title_maps:
      govc: 💫 `govc` (CLI)
      vcsim: 💫 `vcsim` (Simulator)
      chore: 🧹 Chore
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  refs:
    actions:
      - Closes
      - Fixes
  notes:
    keywords:
      - "BREAKING"
